name       : noto-sans-ttf
version    : '20171024'
release    : 14
source     :
    - https://github.com/googlefonts/noto-fonts/archive/v2017-10-24-phase3-second-cleanup.tar.gz : 08d4252dace2367ee1f1d1991c16094a94dc3fa6d9dbd44490335695e0c8d9b4
    - https://github.com/googlefonts/noto-emoji/archive/v2019-11-19-unicode12.tar.gz : 8907563f95c59cfdde796d17284b50bb6ba099a514927020793b0d4d526037e5
extract    : no
license    : OFL-1.1
component  : desktop.font
summary    : Noto Sans Fonts (Multi-lingual and Emoji)
description: |
    Noto Sans Fonts (Multi-lingual and Emoji)
environment: |
    export fonts="NotoSans-* NotoSansDevanagari* NotoKufiArabic* NotoSansGothic* NotoSansKhmer* NotoSansMyanmar* NotoSansSinhala* \
    NotoSansMalayalam* NotoSansBengali* NotoSansGujarati* NotoSansKannada* NotoSansOriya* NotoSansGurmukhi* NotoSansTamil* NotoSansTelugu* NotoSansEthiopic*"
install    : |
    install -Ddm00755 $installdir/usr/share/fonts/truetype/noto-sans-ttf

    #extract it
    for i in $sources/*.tar.gz; do
        tar xf ${i}
    done

    # Install emoji
    install -m00644 noto-emoji-*/fonts/*.ttf $installdir/usr/share/fonts/truetype/noto-sans-ttf

    # Install fonts
    pushd noto-fonts*/hinted
        rm -f *-Extra{Bold,Condensed,Light}*.ttf *.ttc
        for tff in $fonts; do
            install -m00644 $tff $installdir/usr/share/fonts/truetype/noto-sans-ttf
        done
    popd

    find $installdir/ -type d | xargs -I{} chmod 00755 {}
    find $installdir/ -type f | xargs -I{} chmod 00644 {}