name       : noto-sans-ttf
version    : 1
release    : 5
source     :
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip : cea47f7ced337d2e4857b0ef695fe780c13b1f0f494d0a19633d034d404a7874
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDevanagari-hinted.zip : a6d55bfb3fbc9005c18361fe3c83dae2ec7f8278822238bedf2d066cf6f4f57c
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoKufiArabic-hinted.zip : eab8f2c8dd8a97d744cb6e052d88be25e92cae55c4bcb10a5e4702782b513fb3
extract    : no
license    : OFL-1.1
component  : desktop.font
summary    : Noto Sans Fonts
description: |
    Noto Sans Fonts
install    : |
    install -D -d -m 00755 %installroot%/usr/share/doc/noto-sans-ttf
    install -D -d -m 00755 %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    mkdir extractdir && cd extractdir
    for zip in $(ls $sources/*.zip)
    do
        unzip $zip
        install -m 00644 *.ttf %installroot%/usr/share/fonts/truetype/noto-sans-ttf
        cp -f LICENSE_OFL.txt %installroot%/usr/share/doc/noto-sans-ttf
        rm -r *
    done
    cd ../ && rmdir extractdir


    
