name       : noto-sans-ttf
version    : 1
release    : 8
source     :
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip : d9e6edd03fc8b7389bbedee55756e5d047c2b638b01c08f2a22e13d582df5d75
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip : f0584dd57a3b2d8a61a2edaa4ab0e9477d034ee7f5c71ec7b3fca0c94d3a10d2
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDevanagari-hinted.zip : aee4228c102d8c046119fa6851675aa02cdda8248dd70c5f2a8c785590e85702
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoKufiArabic-hinted.zip : 61a8888f2414889c4d5cf1dc4ec07c48ea2965008173f7de0fa9b71d2226031a
extract    : no
license    : OFL-1.1
component  : desktop.font
summary    : Noto Sans Fonts (Multi-lingual and Emoji)
description: |
    Noto Sans Fonts (Multi-lingual and Emoji)
install    : |
    install -D -d -m 00755 %installroot%/usr/share/doc/noto-sans-ttf
    install -D -d -m 00755 %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    mkdir extractdir && cd extractdir
    for zip in $(ls $sources/Noto*-*hinted.zip)
    do
        unzip $zip
        install -m 00644 *.ttf %installroot%/usr/share/fonts/truetype/noto-sans-ttf
        cp -f LICENSE_OFL.txt %installroot%/usr/share/doc/noto-sans-ttf
        rm -r *
    done
    cd ../ && rmdir extractdir


    
