name       : noto-sans-ttf
version    : 1
release    : 4
source     :
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip : cea47f7ced337d2e4857b0ef695fe780c13b1f0f494d0a19633d034d404a7874
license    : OFL-1.1
summary    : Noto Sans Fonts
description: |
    Noto Sans Fonts
install    : |
    install -D -d -m 00755 %installroot%/usr/share/doc/noto-sans-ttf
    install -D -d -m 00755 %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    cp LICENSE_OFL.txt %installroot%/usr/share/doc/noto-sans-ttf
    install -m 00644 *.ttf %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    
