name       : noto-sans-ttf
version    : 2
release    : 10
source     :
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip : d7983299f53742592f61539607c5d9528bcc83639f9a99df94a22c0df4890355
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip : 02e5f834c526f815f3b9f90f98e2b5b09f17cec107cc751c3b58fc3a2c0b2942
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDevanagari-hinted.zip : 6dce0ea53e31d1bc26895ede2992b0acb51836647ec0d67ab988f6b6c3aa08df
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoKufiArabic-hinted.zip : 5fe733749eede0cdba4b97ed621cb73ff9eacb2796489730b5fa4c600ad3c17c
    - https://noto-website-2.storage.googleapis.com/pkgs/NotoSansGothic-hinted.zip : c670f8642000b47a3222f7bd3eb3be4432b75fad5b4822cf1e0d4a9ab5e54b44
extract    : no
license    : OFL-1.1
component  : desktop.font
summary    : Noto Sans Fonts (Multi-lingual and Emoji)
description: |
    Noto Sans Fonts (Multi-lingual and Emoji)
install    : |
    install -Ddm00755 $installdir/usr/share/doc/noto-sans-ttf
    install -Ddm00755 $installdir/usr/share/fonts/truetype/noto-sans-ttf
    mkdir extractdir && cd extractdir
    for zip in $(ls $sources/Noto*-*hinted.zip)
    do
        unzip $zip
        rm -f *-Extra{Bold,Condensed,Light}*.ttf
        install -m00644 *.ttf $installdir/usr/share/fonts/truetype/noto-sans-ttf
        cp -f LICENSE_OFL.txt $installdir/usr/share/doc/noto-sans-ttf
        rm -r *
    done
    cd ../ && rmdir extractdir
    find $installdir/ -type d | xargs -I{} chmod 00755 {}
    find $installdir/ -type f | xargs -I{} chmod 00644 {}

    
