name       : noto-sans-ttf
version    : 1
release    : 3
source     :
    - https://www.google.com/get/noto/pkgs/NotoSans-hinted.zip : 084a3092f0b264b55f51c2f766907c2e5dce1299d5f8cca46a4281c33a2622eb
license    : Apache-2.0
summary    : Noto Sans Fonts
description: |
    Noto Sans Fonts
install    : |
    mkdir -p %installroot%/usr/share/doc/noto-sans-ttf
    mkdir -p %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    cp LICENSE.txt %installroot%/usr/share/doc/noto-sans-ttf
    cp *.ttf %installroot%/usr/share/fonts/truetype/noto-sans-ttf
    
