name       : noto-sans-ttf
version    : '2.7'
release    : 15
source     :
    - https://github.com/googlefonts/noto-fonts/archive/v2.7-NotoSlimVF.tar.gz : edcf0d838ae0aeac580bd2cc322d493e1eb42179bf2cbba7caf024501e1fc25f
    - https://github.com/googlefonts/noto-emoji/archive/v2019-11-19-unicode12.tar.gz : 8907563f95c59cfdde796d17284b50bb6ba099a514927020793b0d4d526037e5
extract    : no
license    : OFL-1.1
component  : desktop.font
summary    : Noto Sans Fonts (Multi-lingual and Emoji)
description: |
    Noto Sans Fonts (Multi-lingual and Emoji)
environment: |
    export fonts="NotoSans NotoSansDevanagari NotoSansDevanagariUI NotoKufiArabic NotoSansGothic NotoSansKhmer NotoSansKhmerUI NotoSansMyanmar NotoSansMyanmarUI \
    NotoSansSinhala NotoSansSinhalaUI NotoSansMalayalam NotoSansMalayalamUI NotoSansBengali NotoSansBengaliUI NotoSansGujarati NotoSansGujaratiUI NotoSansKannada \
    NotoSansKannadaUI NotoSansOriya NotoSansOriyaUI NotoSansGurmukhi NotoSansGurmukhiUI NotoSansTamil NotoSansTamilUI NotoSansTelugu NotoSansTeluguUI NotoSansEthiopic"
install    : |
    install -Ddm00755 $installdir/usr/share/fonts/truetype/noto-sans-ttf

    #extract it
    for i in $sources/*.tar.gz; do
        tar xf ${i}
    done

    # Install emoji
    install -m00644 noto-emoji-*/fonts/*.ttf $installdir/usr/share/fonts/truetype/noto-sans-ttf

    # Install fonts
    for tff in $fonts; do
        pushd noto-fonts*/hinted/$tff
            rm -f *-{Black,Extra}*.ttf *.ttc
            install -m00644 $tff-* $installdir/usr/share/fonts/truetype/noto-sans-ttf
        popd
    done

    # Install fontconfig files
    install -Dm00644 $pkgfiles/66-noto-color-emoji.conf -t $installdir/usr/share/fonts/conf.d

    install -dm00644 $installdir/etc/fonts/conf.d
    ln -sv $installdir/usr/share/fonts/conf.d/66-noto-color-emoji.conf $installdir/etc/fonts/conf.d/.

    find $installdir/ -type d | xargs -I{} chmod 00755 {}
    find $installdir/ -type f | xargs -I{} chmod 00644 {}
